### ISSUE TITLE
Support BIP39 Mnemonic Phrases for HD Wallet Seed

### ISSUE THREAD

**Issue by collinc97** [ArgusHQ/wagu#9]
Mnemonic Phrases - [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki)
HD Wallets - [BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)
Test Vectors - [Here](https://github.com/trezor/python-mnemonic/blob/master/vectors.json)

Tasks:
- [x] mnemonic generation
- [x] mnemonic import
- [x] test vectors

**Comment by collinc97** [comment]
hd wallet generation, mnemonic generation from entropy, hd wallet seed generation from password salt implemented: e318e5008e872e3f41d481d096eda25b13a85615

**Comment by howardwu** [comment]
#23
